### ISSUE TITLE
Potential Incorrect Screenshot

### ISSUE THREAD

**Issue by Cyb3rC3lt** [AlmondOffSec/PassTheCert#14]
Hi guys,

I was using your brilliant tool today which got me DA eventually, but I think I noticed an issue in this screenshot. In this it seems you added the delegation to your Dummy computer which you added with add computer but really the attribute should be added the other way round. So the attribute goes onto the DC (in my case) specifying the Dummy computer.

As soon as I did that it worked fine.

Hope this helps

![pass_the_cert_python](https://github.com/AlmondOffSec/PassTheCert/assets/33097451/7fef5b2e-7189-4efc-9850-11e7f83fda2e)

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
Hello,
I'm glad our tool got you DA! I took this screenshot to illustrate the blog post and to show 3 functions: add computer via implicite TLS, add computer via explicite TLS and RBCD via Schannel. The goal was not to show a real case scenario, but only few exemples. Sorry if it misled you.

:sunflower:

**Comment by Cyb3rC3lt** [comment]
Ah fair enough, I thought it was a playbook. Thanks for the reply 👍🏻
