### ISSUE TITLE
socket ssl wrapping error: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by esvevan** [AlmondOffSec/PassTheCert#16]
I have been able to interact with both ldap and ldaps in various different contexts including flagging both ldap and ldaps via certipy, and ldapdomaindump, so this doesn't seem that this is an environmental issue.  Connecting to the DC with  openssl s_client -connect $DC_IP:636 returns "Can't use SSL_get_servername" but connects and the DC response with the certificate.  Any command I attempt with passthecert.py results in the following error:

Impacket v0.11.0 - Copyright 2023 Fortra

[+] Impacket Library Installation Path: /usr/lib/python3/dist-packages/impacket
Traceback (most recent call last):
  File "/root/tools/PassTheCert/Python/passthecert.py", line 653, in <module>
    ldapConn.open()
  File "/usr/lib/python3/dist-packages/ldap3/strategy/sync.py", line 57, in open
    BaseStrategy.open(self, reset_usage, read_server_info)
  File "/usr/lib/python3/dist-packages/ldap3/strategy/base.py", line 146, in open
    raise exception_history[0][0]
ldap3.core.exceptions.LDAPSocketOpenError: socket ssl wrapping error: [Errno 2] No such file or directory
socket ssl wrapping error: [Errno 2] No such file or directory

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
Hello!

Can you also provide the passthecert command line please ? According to the exception, your problem is mostly related to the SSL connection, `No such file or directory` seems to be a path error: are you sure paths after `-key` and `-cert` are correct?

:sunflower:
