### ISSUE TITLE
Is PassTheCert right for a shadow credentials job?

### ISSUE THREAD

**Issue by 7MinSec** [AlmondOffSec/PassTheCert#20]
Hello AlmondOffSec friends!

I'm in a situation where I'm trying to figure out if PassTheCert is the right tool for this conundrum I'm in.  I've followed [this article](https://www.fortalicesolutions.com/posts/shadow-credentials-workstation-takeover-edition) to use ntlmrelayx + printerbug to relay and then edit the msds-keycredentiallink attribute of VICTIM-SERVER.  When I take the next step of using `gettgtpkinit.py` to request a TGT, I get a long error mentioning `KDC has no support for PADATA`.  

Google searches led me here, and I see some mention of using PassTheCert for shadow creds in issue https://github.com/AlmondOffSec/PassTheCert/issues/18 but I'm not sure if/how it applies to my situation.  My goal is to get a TGT for VICTIM-SERVER and then use Kerberos S4U2Self to get a TGS for a service on the host.  

Is PassTheCert the right tool for this?

**Comment by 7MinSec** [comment]
Note to self - according to [this article](https://github.com/ShutdownRepo/pywhisker?tab=readme-ov-file) I might be a no-go because of conditions needed for this attack to work (?)

![image](https://github.com/AlmondOffSec/PassTheCert/assets/17596787/4eb23336-ab59-4d9c-a993-185e773fe65c)

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
Hello!

Long story short: no you can't use certificate set during shadowcredz attack to do schannel authentication. Thus, no, PasTheCert is not the right tool for this.

AFAIK shadow credentials uses PKINIT (a kerberos extension based on certificate) and pass the cert leverages TLS authentication (mutual authentication, part of the spec). 

Even if both attacks "use" certificates, the important point imo is "what is the trusted attribute?": on one hand, PKINIT, the DC trusts an LDAP attribute which contains a **self-signed certificate**. On the other hand (schannel), the DC trusts a TLS certificate **signed** by a trusted CA.

> according to [this article](https://github.com/ShutdownRepo/pywhisker?tab=readme-ov-file) I might be a no-go because of conditions needed for this attack to work (?)

According to some tests I've done before, in both cases the DC needs its own certificate : for PKINIT, DC needs EKU `Smart Card Logon EKU` and for SChannel it needs EKU `Server Authentication` (see also [this](https://posts.specterops.io/certificates-and-pwnage-and-patches-oh-my-8ae0f4304c1d)).

:sunflower:

**Comment by 7MinSec** [comment]
Thanks so much for the super thorough response.  I won't spend any more time chasing this lead.
