### ISSUE TITLE
KDC_ERR_BADOPTION

### ISSUE THREAD

**Issue by jsdhasfedssad** [AlmondOffSec/PassTheCert#3]
Hi,

I very much look forward to use your tool! However, when I tested it in my lab environment today I am unable to request silver tickets. I get the error "Kerberos SessionError: KDC_ERR_BADOPTION(KDC cannot accommodate requested option)". See the picture below:

![passthecertb](https://user-images.githubusercontent.com/97032878/182400798-03a8d34c-6180-4df9-b85c-33ade2390d56.png)

This is strange since when I perform the same RBCD attack using BloodyAD and the same DC (dc2$) this works. See the picture below:
![bloodyadb](https://user-images.githubusercontent.com/97032878/182401205-f7834746-de52-4a26-bdf6-9c123cd4b6e0.png)

To me it seems that something is broken with the writing of the delegation rights in the case of your tool.

Any ideas? Thanks!

**Comment by the-useless-one** [comment]
HI @jsdhasfedssad,

I think you switched `-delegate-to` and `-delegate-from` in your first screenshot. From the Python's [README](https://github.com/AlmondOffSec/PassTheCert/tree/main/Python#usage):

```
  -delegate-to DELEGATE_TO
                        Target computer account the attacker has at least WriteProperty to
  -delegate-from DELEGATE_FROM
                        Attacker controlled machine account to write on the msDS-Allo[...] property (only when using `-action write`)
```

Try with `-delegate-to dc2$ -delegate-from test12$` and let me know if that works.

**Comment by jsdhasfedssad** [comment]
I actually tested that before. When I try that I get a different error:

![passthecertc](https://user-images.githubusercontent.com/97032878/182411221-d15b6d90-b2fc-4ae7-81fc-571bbe7be26f.png)

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
Hello @jsdhasfedssad

Your last command is the correct one. Can you try the same command with the `-debug` option please ? It seems that a SID is already set in the attribute but it is no longer existing within the LDAP.

🌻

**Comment by jsdhasfedssad** [comment]
Sure! Here you go.

![passthecertd](https://user-images.githubusercontent.com/97032878/182608654-4da26d3a-29b4-4a5d-92dd-db9df5a1d34e.png)

**Comment by the-useless-one** [comment]
I agree with @ThePirateWhoSmellsOfSunflowers: the script is reading the `msDS-AllowedToActOnBehalfOfOtherIdentity` attribute of your DC, tries to resolve every SID in it to pretty-print the `sAMAccountName`, but fails in your case because the SID does not point to anything anymore.

I created a [new branch](https://github.com/AlmondOffSec/PassTheCert/tree/fix_sid_resolve) to try and fix this behavior: in case the SID does not resolve, two placeholder strings are returned instead of a `False`. Could you give it a try and tell us if it fixes your problem?

**Comment by jsdhasfedssad** [comment]
I cloned the new branch and tested but I get the exact same error message as before.

**Comment by the-useless-one** [comment]
Could you `git pull` and try again? I didn't put the fix in the right function... :eyes:

**Comment by jsdhasfedssad** [comment]
Great! This now works. Thanks!

![passthecerte](https://user-images.githubusercontent.com/97032878/182846465-f28a7034-6b0e-479f-980d-fccffd376426.png)

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
Hi all,

FYI, I've just merged the fix into `main`.
Thanks again @jsdhasfedssad

:sunflower:
